PL/Controllers/VueloController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace PL.Controllers
{
    public class VueloController : Controller
    {
        [HttpGet]
        public ActionResult GetAll()
        {
            ML.Vuelo vuelo = new ML.Vuelo();
            ML.Result result = new ML.Result();
            result.Objects = new List<object>();

            vuelo.FechaInicio = (vuelo.FechaInicio == null) ? "0" : vuelo.FechaInicio; //Operador ternario
            vuelo.FechaFin = (vuelo.FechaFin == null) ? "0" : vuelo.FechaFin;

            string urlAPI = System.Configuration.ConfigurationManager.AppSettings["URLapi"];

            //Inicia Servicio
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(urlAPI);

                var responseTask = client.GetAsync("Vuelo/GetAll/" + vuelo.FechaInicio + ", " + vuelo.FechaFin);
                responseTask.Wait();

                var resultService = responseTask.Result;

                if (resultService.IsSuccessStatusCode)
                {
                    var readTask = resultService.Content.ReadAsAsync<ML.Result>();
                    readTask.Wait();

                    foreach (var resultItem in readTask.Result.Objects)
                    {
                        vuelo = Newtonsoft.Json.JsonConvert.DeserializeObject<ML.Vuelo>(resultItem.ToString());
                        result.Objects.Add(vuelo);
                        vuelo.Vuelos = result.Objects;
                    }
                }
            }

            return View(vuelo);
        }

        [HttpPost]
        public ActionResult GetAll(ML.Vuelo vuelo)
        {
            ML.Result result = new ML.Result();
            result.Objects = new List<object>();

            vuelo.FechaInicio = (vuelo.FechaInicio == null) ? "0" : vuelo.FechaInicio; //Operador ternario
            vuelo.FechaFin = (vuelo.FechaFin == null) ? "0" : vuelo.FechaFin;

            string urlAPI = System.Configuration.ConfigurationManager.AppSettings["URLapi"];

            //Inicia Servicio
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(urlAPI);

                var responseTask = client.GetAsync("Vuelo/GetAll/" + vuelo.FechaInicio + ", " + vuelo.FechaFin);
                responseTask.Wait();

                var resultService = responseTask.Result;

                if (resultService.IsSuccessStatusCode)
                {
                    var readTask = resultService.Content.ReadAsAsync<ML.Result>();
                    readTask.Wait();

                    foreach (var resultItem in readTask.Result.Objects)
                    {
                        vuelo = Newtonsoft.Json.JsonConvert.DeserializeObject<ML.Vuelo>(resultItem.ToString());
                        result.Objects.Add(vuelo);
                        vuelo.Vuelos = result.Objects;
                    }
                }
            }

            return View(vuelo);
        }
    }
}

PL/Views/Vuelo/GetAll.cshtml
@model ML.Vuelo
@{
    ViewBag.Title = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <h2>Vuelos</h2>
            <hr />
        </div>
    </div>
    <br />

    <div class="align-content-center">
        @using (Html.BeginForm("GetAll", "Vuelo", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <div class="row">
                <div class="col-md-4">
                    @Html.LabelFor(model => model.FechaInicio)
                    @Html.TextBoxFor(model => model.FechaInicio, new { @class = "form-control", @placeholder = "yyyy/MM/dd", @autocomplete = "off" })
                </div>
                <div class="col-md-4">
                    @Html.LabelFor(model => model.FechaFin)
                    @Html.TextBoxFor(model => model.FechaFin, new { @class = "form-control", @placeholder = "yyyy/MM/dd", @autocomplete = "off" })
                </div>
            </div>
            <br />
            <div class="row justify-content-end">
                @* Justificar todo a la derecha (al final) *@
                <div class="col-md-4">
                    <input type="submit" value="Buscar" class="btn btn-primary float-end" formmethod="post"> @* La clase float-end mueve a la derecha el elemento *@
                </div>
            </div>
            <br />
        }
    </div>

    @if (Model.Vuelos.Count > 0)
    {
        <div class="row">
            <div class="col-lg-12">
                <table class="table table-bordered table-responsive">
                    <thead>
                        <tr class="text-center">
                            <td>Editar</td>
                            <td class="form-group" style="display: none;">IdVuelo</td>
                            <td>Origen</td>
                            <td>Destino</td>
                            <td>Fecha de Inicio</td>
                            <td>Fecha de Fin</td>
                            <td>Fecha de Salida</td>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (ML.Vuelo vuelo in Model.Vuelos)
                        {
                            <tr class="text-center">
                                <td><a class="btn btn-warning glyphicon glyphicon-edit" href="@Url.Action("Form", "Vuelo", new { VueloNumero = vuelo.VueloNumero })"></a></td>
                                <td class="form-group" style="display: none;">@vuelo.VueloNumero</td>
                                <td>@vuelo.Origen</td>
                                <td>@vuelo.Destino</td>
                                <td>@vuelo.FechaInicio</td>
                                <td>@vuelo.FechaFin</td>
                                <td>@vuelo.FechaSalida</td>                               
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    }
    else
    {
        <div class="row">
            <div class="col-lg-12">
                <div class="alert alert-danger" role="alert">
                    No se encontraron vuelos disponibles!!!
                </div>
            </div>
        </div>
    }

</div>