PL/Controllers/PasajeroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace PL.Controllers
{
    public class PasajeroController : Controller
    {
        // GET: Pasajero
        [HttpGet]
        public ActionResult Form()
        {
            ML.Pasajero pasajero = new ML.Pasajero();

            return View(pasajero);
        }

        [HttpPost]
        public ActionResult Form(ML.Pasajero pasajero)
        {
            //Inicia servicio
            using (var client = new HttpClient())
            {
                string urlAPI = System.Configuration.ConfigurationManager.AppSettings["URLapi"];
                client.BaseAddress = new Uri(urlAPI);

                var postTask = client.PostAsJsonAsync<ML.Pasajero>("Pasajero/Add", pasajero);
                postTask.Wait();

                var resultAdd = postTask.Result;
                if (resultAdd.IsSuccessStatusCode)
                {
                    ViewBag.Message = "El pasajero se ingresó correctamente!!!";
                }
                else
                {
                    ViewBag.Message = "Ocurrió un error al momento de ingresar el pasajero";
                }
            }

            return PartialView("ValidationModal");
        }
    }
}

PL/Views/Pasajero/Form.cshtml
@model ML.Pasajero
@{
    ViewBag.Title = "Form";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid">
    <div class="row">
        <div class="col-md-6">
            <h1>Añadir Pasajero</h1>
            <hr />
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <h5 class="text-left">Llene los campos con la información del pasajero que desea registrar de acuerdo a lo que se indica.</h5>
        </div>
    </div>
    <hr />
    <div class="row">
        <div class="col-md-12">
            @using (Html.BeginForm("Form", "Pasajero", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group" style="display: none;">
                            @Html.LabelFor(model => model.IdPasajero, new { @class = "hidden" })
                            @Html.TextBoxFor(model => model.IdPasajero, new { @class = "hidden form-control", autocomplete = "off" })
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        @Html.LabelFor(model => model.Nombres)
                        <div class="input-group">
                            <span class="input-group-text" id="basic-addon1"><i class="bi bi-alarm"></i></span>
                            @Html.TextBoxFor(model => model.Nombres, new { @class = "form-control", @autocomplete = "off" })
                        </div>
                        @Html.ValidationMessageFor(model => model.Nombres)
                    </div>
                    <div class="col-md-6">
                        @Html.LabelFor(model => model.Apellidos)
                        <div class="input-group">
                            <span class="input-group-text" id="basic-addon1"><i class="bi bi-telephone"></i></span>
                            @Html.TextBoxFor(model => model.Apellidos, new { @class = "form-control", autocomplete = "off" })
                        </div>
                        @Html.ValidationMessageFor(model => model.Apellidos)
                    </div>
                </div>
                <br />

                <div class="row">
                    <div class="col-md-1">
                        <input type="submit" value="Guardar" class="btn btn-success">
                    </div>
                </div>
            }

        </div>
    </div>
</div>

PL/Views/Pasajero/ValidationModal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="modalValidacion">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Message</h5>
            </div>
            <div class="modal-footer">
                @Html.ActionLink("Regresar", "Index", "Home", htmlAttributes: new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
</div>

<script>
    $('#modalValidacion').modal();
</script>