PL/Controllers/ReservacionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net.Http;
using System.Configuration;

namespace PL.Controllers
{
    public class ReservacionController : Controller
    {
        // GET: Reservacion
        [HttpGet]
        public ActionResult PasajeroGetAll()
        {
            //ML.Result resultPasajeros = BL.Pasajero.GetAll();
            ML.Pasajero pasajero = new ML.Pasajero();
            ML.Result result = new ML.Result();
            result.Objects = new List<object>();

            string urlAPI = System.Configuration.ConfigurationManager.AppSettings["URLapi"];

            //Inicia Servicio
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(urlAPI);

                var responseTask = client.GetAsync("Pasajero/GetAll");
                responseTask.Wait();

                var resultService = responseTask.Result;

                if (resultService.IsSuccessStatusCode)
                {
                    var readTask = resultService.Content.ReadAsAsync<ML.Result>();
                    readTask.Wait();

                    foreach (var resultItem in readTask.Result.Objects)
                    {
                        pasajero = Newtonsoft.Json.JsonConvert.DeserializeObject<ML.Pasajero>(resultItem.ToString());
                        result.Objects.Add(pasajero);
                        pasajero.Pasajeros = result.Objects;
                    }
                }

                ML.VueloPasajero vueloPasajero = new ML.VueloPasajero();
                vueloPasajero.Pasajero = new ML.Pasajero();

                if (pasajero.Pasajeros != null)
                {
                    vueloPasajero.Pasajero.Pasajeros = pasajero.Pasajeros;
                    return View(vueloPasajero);
                }
                else
                {
                    ViewBag.Message = "No se encontraron pasajeros";
                    return PartialView("ValidationModal");
                }
            }
        }

        [HttpGet]
        public ActionResult AsignarVuelo(int IdPasajero)
        {
            ML.Vuelo vuelo = new ML.Vuelo();
            ML.VueloPasajero vueloPasajero = new ML.VueloPasajero();
            ML.Result result = new ML.Result();
            result.Objects = new List<object>();
            //ML.Result resultVuelos = BL.VueloPasajero.VueloGetByIdPasajero(IdPasajero);

            string urlAPI = System.Configuration.ConfigurationManager.AppSettings["URLapi"];

            //Inicia Servicio
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(urlAPI);

                var responseTask = client.GetAsync("VueloPasajero/GetById/" + IdPasajero);
                responseTask.Wait();

                var resultService = responseTask.Result;

                if (resultService.IsSuccessStatusCode)
                {
                    var readTask = resultService.Content.ReadAsAsync<ML.Result>();
                    readTask.Wait();

                    foreach (var resultItem in readTask.Result.Objects)
                    {
                        vueloPasajero = Newtonsoft.Json.JsonConvert.DeserializeObject<ML.VueloPasajero>(resultItem.ToString());
                        result.Objects.Add(vueloPasajero);
                        vueloPasajero.VueloPasajeros = result.Objects;
                    }
                }

                vueloPasajero.Pasajero = new ML.Pasajero();

                if (vueloPasajero.VueloPasajeros != null)
                {
                    vueloPasajero.Pasajero.IdPasajero = IdPasajero;
                    return View(vueloPasajero);
                }
                else
                {
                    ViewBag.Message = "No se encontraron pasajeros";
                    return PartialView("ValidationModal");
                }
            }
        }

        [HttpGet]
        public ActionResult VuelosNoAsignados(int IdPasajero)
        {
            ML.VueloPasajero vueloPasajero = new ML.VueloPasajero();
            ML.Result result = new ML.Result();
            result.Objects = new List<object>();
            //ML.Result resultVuelos = BL.VueloPasajero.VueloGetNoAsignado(IdPasajero);

            string urlAPI = System.Configuration.ConfigurationManager.AppSettings["URLapi"];

            //Inicia Servicio
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(urlAPI);

                var responseTask = client.GetAsync("VueloPasajero/VueloGetNoAsignados/" + IdPasajero);
                responseTask.Wait();

                var resultService = responseTask.Result;

                if (resultService.IsSuccessStatusCode)
                {
                    var readTask = resultService.Content.ReadAsAsync<ML.Result>();
                    readTask.Wait();

                    foreach (var resultItem in readTask.Result.Objects)
                    {
                        vueloPasajero = Newtonsoft.Json.JsonConvert.DeserializeObject<ML.VueloPasajero>(resultItem.ToString());
                        result.Objects.Add(vueloPasajero);
                        vueloPasajero.VueloPasajeros = result.Objects;
                    }
                }

                vueloPasajero.Pasajero = new ML.Pasajero();

                if (vueloPasajero.VueloPasajeros != null)
                {
                    vueloPasajero.Pasajero.IdPasajero = IdPasajero;
                    return View(vueloPasajero);
                }
                else
                {
                    ViewBag.Message = "No se encontraron pasajeros";
                    return PartialView("ValidationModal");
                }
            }
        }

        [HttpPost]
        public ActionResult VuelosNoAsignados(ML.VueloPasajero vueloPasajero)
        {
            vueloPasajero.Vuelo = new ML.Vuelo();

            if(vueloPasajero.VueloPasajeros != null)
            {
                int i = 0;

                foreach (string vueloNumero in vueloPasajero.VueloPasajeros)
                {
                    //ML.Result result = BL.VueloPasajero.ReservacionAdd(vueloNumero, vueloPasajero.Pasajero.IdPasajero);
                    vueloPasajero.IdVueloPasajero = i;

                    //Inicia Servicio
                    using (var client = new HttpClient())
                    {
                        string urlAPI = System.Configuration.ConfigurationManager.AppSettings["URLapi"];
                        client.BaseAddress = new Uri(urlAPI);

                        var postTask = client.PostAsJsonAsync<ML.VueloPasajero>("VueloPasajero/VueloGetNoAsignados", vueloPasajero);
                        postTask.Wait();

                        var resultAdd = postTask.Result;
                        if (resultAdd.IsSuccessStatusCode)
                        {
                            ViewBag.Message = "El vuelo se asignó correctamente!!!";
                        }
                        else
                        {
                            ViewBag.Message = "Ocurrió un error al momento de asignar el vuelo";
                        }
                    }
                    i++;
                }
            }

            return PartialView("ValidationModal", vueloPasajero);
        }
    }
}

PL/Views/Reservacion/AsignarVuelo.cshtml
@model ML.VueloPasajero
@{
    ViewBag.Title = "AsignarVuelo";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h2>Vuelos-Pasajero</h2>
            <hr />
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <h6 class="text-center">Selecione el boton "+" para añadir un vuelo al pasajero </h6>
        </div>
    </div>
    <br />

    <div class="row">
        <div class="col-md-12">
            <div class="form-group" style="display: none;">
                @Html.LabelFor(model => model.IdVueloPasajero, new { @class = "hidden" })
                @Html.TextBoxFor(model => model.IdVueloPasajero, new { @class = "hidden form-control" })
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            @Html.LabelFor(model => model.Pasajero.IdPasajero, new { @class = "hidden form-control" })
            @Html.TextBoxFor(model => model.Pasajero.IdPasajero, new { @class = "hidden form-control" })
        </div>
    </div>

    <div class="row">
        <div class="col-md-1">
            <table class="table table-bordered table-responsive">
                <thead>
                    <tr class="text-left">
                        <td><a class="btn btn-primary glyphicon glyphicon-blackboard" href="@Url.Action("VuelosNoAsignados", "Reservacion", new { IdPasajero = Model.Pasajero.IdPasajero})"></a></td>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
    <br />

    @if (Model.VueloPasajeros.Count > 0)
    {
        <div class="row">
            <div class="col-md-12">
                <h4>Vuelos</h4>
                <hr />
            </div>
        </div>
        <br />

        <div class="row">
            <div class="col-md-12">
                <table class="table table-bordered table-responsive">
                    <thead>
                        <tr class="text-center">
                            <td class="form-group" style="display: none;">IdVuelo</td>
                            <td>Origen</td>
                            <td>Destino</td>
                            <td>Fecha de Inicio</td>
                            <td>Fecha de Fin</td>
                            <td>Fecha de Salida</td>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach (ML.VueloPasajero vuelo in Model.VueloPasajeros)
                        {
                            <tr class="text-center">
                                <td class="form-group" style="display: none;">@vuelo.Vuelo.VueloNumero</td>
                                <td>@vuelo.Vuelo.Origen</td>
                                <td>@vuelo.Vuelo.Destino</td>
                                <td>@vuelo.Vuelo.FechaInicio</td>
                                <td>@vuelo.Vuelo.FechaFin</td>
                                <td>@vuelo.Vuelo.FechaSalida</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    }
    else
    {
        <div class="row">
            <div class="col-xl-12">
                <div class="alert alert-danger" role="alert">
                    No se encontraron registros de vuelos para este pasajero!!!
                </div>
            </div>
        </div>
    }


</div>

PL/Views/Reservacion/PasajeroGetAll.cshtml
@model ML.VueloPasajero
@{
    ViewBag.Title = "PasajeroGetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <h2>Reservar Vuelos</h2>
            <hr />
        </div>
    </div>
    <div class="row">
        <div class="col-lg-6">
            <h5 class="text-center">Seleccione el boton de "+" para añadir un vuelo a un pasajero</h5>
        </div>
    </div>
    <br />

    @if (Model.Pasajero.Pasajeros.Count > 0)
    {
        <div class="row">
            <div class="col-lg-12">
                <table class="table table-bordered table-responsive">
                    <thead>
                        <tr class="text-center">
                            <td>Asignar vuelo</td>
                            <td class="form-group" style="display: none;">IdPasajero</td>
                            <td>Nombre</td>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (ML.Pasajero pasajero in Model.Pasajero.Pasajeros)
                        {
                            <tr class="text-center">
                                <td><a class="btn btn-warning glyphicon glyphicon-edit" href="@Url.Action("AsignarVuelo", "Reservacion", new { IdPasajero = pasajero.IdPasajero })"></a></td>
                                <td class="form-group" style="display: none;">@pasajero.IdPasajero</td>
                                <td>@pasajero.Nombres @pasajero.Apellidos</td>                               
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    }
    else
    {
        <div class="row">
            <div class="col-lg-12">
                <div class="alert alert-danger" role="alert">
                    No se encontraron pasajeros disponibles!!!
                </div>
            </div>
        </div>
    }

</div>

PL/Views/Reservacion/ValidationModal.cshtml
@model ML.VueloPasajero
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="modalValidacion">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Message</h5>
            </div>
            <div class="modal-footer">
                @Html.ActionLink("Regresar", "AsignarVuelo", "Reservacion", new { IdPasajero = Model.Pasajero.IdPasajero }, htmlAttributes: new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
</div>

<script>
    $('#modalValidacion').modal();
</script>

PL/Views/Reservacion/VuelosNoAsignados.cshtml
@model ML.VueloPasajero
@{
    ViewBag.Title = "VuelosNoAsignados";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <h2>Vuelos</h2>
            <hr />
        </div>
    </div>
    <div class="row">
        <div class="col-lg-6">
            <h5 class="text-center">Seleccione los vuelos que desea asignar al pasajero y de clic en Asignar</h5>
        </div>
    </div>

    <div class="row">
        <h4>Asignar Vuelos</h4>
    </div>
    <br />

    <div class="row">

        @using (Html.BeginForm("VuelosNoAsignados", "Reservacion", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <div class="row">
                <div class="col-md-4">
                    @Html.TextBoxFor(model => model.Pasajero.IdPasajero, new { @class = "hidden form-control" })
                </div>
            </div>
            @*<div class="row">
                <div class="col-md-4">
                    @Html.LabelFor(model => model.Alumno.Nombre)
                    @Html.TextBoxFor(model => model.Alumno.Nombre, new { @class = "form-control", disabled = "true" })
                </div>
                <div class="col-md-4">
                    @Html.LabelFor(model => model.Alumno.ApellidoPaterno)
                    @Html.TextBoxFor(model => model.Alumno.ApellidoPaterno, new { @class = "form-control", disabled = "true" })
                </div>
                <div class="col-md-4">
                    @Html.LabelFor(model => model.Alumno.ApellidoMaterno)
                    @Html.TextBoxFor(model => model.Alumno.ApellidoMaterno, new { @class = "form-control", disabled = "true" })
                </div>
            </div>*@
            <br />

            if (Model.VueloPasajeros.Count > 0)
            {
                <div class="row">
                    <div class="col-lg-12">
                        <table class="table table-bordered table-responsive">
                            <thead>
                                <tr class="text-center">
                                    <td class="form-group" style="display: none;">VueloNumero</td>
                                    <td>Asignar</td>
                                    <td>Origen</td>
                                    <td>Destino</td>
                                    <td>Fecha de Salida</td>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (ML.VueloPasajero vueloPasajero in Model.VueloPasajeros)
                                {

                                    <tr class="text-center">
                                        <td class="form-group" style="display: none;">@vueloPasajero.Vuelo.VueloNumero</td>
                                        @*<td><input class="form-check-input" name="alumnoMateria.AlumnoMaterias" type="checkbox" value="@alumnoMateria.Materia.IdMateria"></td>*@
                                        <td class="text-center"><input type="checkbox" name="VueloPasajeros" value="@vueloPasajero.Vuelo.VueloNumero" /></td>
                                        <td>@vueloPasajero.Vuelo.Origen</td>
                                        <td>@vueloPasajero.Vuelo.Destino</td>
                                        <td>@vueloPasajero.Vuelo.FechaSalida</td>
                                    </tr>


                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            }
            else
            {
                <div class="row">
                    <div class="col-lg-12">
                        <div class="alert alert-danger" role="alert">
                            El pasajero ya está registrado en todos los vuelos disponibles!!!
                        </div>
                    </div>
                </div>
            }

            <div class="row">
                <div class="col-md-1">
                    <input type="submit" value="Asignar" class="btn btn-success">

                </div>
                <div class="col-md-1">
                    <a type="submit" class="btn btn-danger" href="@Url.Action("AsignarVuelo", "Reservacion", new { IdPasajero = Model.Pasajero.IdPasajero })">Regresar </a>
                </div>
            </div>
        }

    </div>



</div>